CONTIKI_PROJECT = udp-broadcast-sender udp-broadcast-receiver
all: $(CONTIKI_PROJECT)

CFLAGS += -DPROJECT_CONF_H=\"project-conf.h\"

#THSQAPPS+=replong

CONTIKI=../..

SMALL=1
#IAR=1

include $(CONTIKI)/Makefile.include
